---
repo_url: https://github.com/jonh-carvalho/PBE_26.1_8001
site_author: Jonh Carvalho
site_name: PBE_26.1_8001
copyright: Copyright ©️ 2026, Jonh Carvalho

nav: 
  - Home: index.md
  - Disciplina:
      - Aulas: Disciplina/aulas.md
      - Streaming: 
            - Projeto Streaming: Disciplina/Roteiros/Construcao/Streaming/00_Projeto_Streaming.md
            - Regras de Negócio: Disciplina/Roteiros/Construcao/Streaming/01_Regras_Negocio.md
            - Modelagem: Disciplina/Roteiros/Construcao/Streaming/02_Modelagem.md
            - Rest API: Disciplina/Roteiros/Construcao/Streaming/03_Rest.md
            - Consumo API: Disciplina/Roteiros/Construcao/Streaming/04_Consume.md
            - Diag. de Sequência: Disciplina/Roteiros/Construcao/Streaming/04_Diagrama_Sequencia.md
            - Relacionamentos: Disciplina/Roteiros/Construcao/Streaming/05_Playlist_NxN.md
            - Shell: Disciplina/Roteiros/Construcao/Streaming/06_Shell.md
            - Swagger: Disciplina/Roteiros/Construcao/Streaming/07_Swagger.md
            - CorsOrigin: Disciplina/Roteiros/Construcao/Streaming/08_CorsOrigin.md
            - Consumo Frontend: Disciplina/Roteiros/Construcao/Streaming/09_Consume_Web.md
            - Admin: Disciplina/Roteiros/Construcao/Streaming/10_Admin.md
            - Autenticação: Disciplina/Roteiros/Construcao/Streaming/12_Autentication.md
            - Filtros: Disciplina/Roteiros/Construcao/Streaming/13_Filtros.md
            - Regras de Negócio Avançadas: Disciplina/Roteiros/Construcao/Streaming/14_Regras_Negocio.md
            - Deploy: Disciplina/Roteiros/Construcao/Streaming/15_Deploy.md
      - Roteiros:
        - Iniciação: 
          - DT: Disciplina/Roteiros/Iniciacao/04_DesignThinking.md
          - RUP/UP: Disciplina/Roteiros/Iniciacao/04_RUPgithub.md
        - Elaboração:
          - RUP/UP: Disciplina/Roteiros/Elaboracao/06_LevantamentoRequisitos.md
        - Construção:
          - POO:
            - POO: Disciplina/Roteiros/Construcao/Poo/poo.ipynb
            - POO Django: Disciplina/Roteiros/Construcao/Poo/poo_django.ipynb
          - Django:
            - Django: Disciplina/Roteiros/Construcao/Django/01_Intro.md
            - Django Rest: Disciplina/Roteiros/Construcao/Django/02_Intro_Django_Rest.md
            - Api Consume: Disciplina/Roteiros/Construcao/Django/03_Consume.md
          - BD:
            - Intro SQL: Disciplina/Roteiros/Construcao/BD/pysqlite.ipynb
            - SQL: Disciplina/Roteiros/Construcao/BD/sqlite.md 
      - Github: Disciplina/github.md
      - Mkdocs: Disciplina/mkdocs.md
      - Avaliações: Disciplina/avaliacoes.md
      
  - Iniciação: 
      - Index: Iniciacao/index.md
      - Pesquisa: Iniciacao/pesquisa.md
      - 5w2h: Iniciacao/5w2h.md
      - Design Thinking: Iniciacao/design_thinking.md
      - Brainstorming: Iniciacao/Brainstorm.md
      - Mapa Mental: Iniciacao/mapa_mental.md
      - Prototipagem Baixa Fidelidade: Iniciacao/prototipo_baixa_fidelidade.md
  - Elaboração:
      - Index: Elaboracao/index.md
      - Requisitos: Elaboracao/levreq.md
      - Casos de Uso: Elaboracao/casos_de_uso.md
      - Diagrama de Classes: Elaboracao/diagrama_de_classes.md
      - Diagrama de Sequência: Elaboracao/diagrama_de_sequencia.md
  - Construção:
      - Index: Construcao/index.md
      - Github Workflows: Construcao/github_workflows.md
      - GitHub Projects: Construcao/github_projects.md
      - CodeSpace: Construcao/codespace.md
  - Transição:
      - Index: Transicao/index.md

  - Bibliografia: Disciplina/Bibliografia.md

extra_css:
  - css/extra.css

markdown_extensions:
  # Tooltips
  - abbr
  # Admonitions
  - admonition
  # Annotations, Buttons, Grids, Icons & Emojis, Images, Tooltips
  - attr_list
  # Footnotes
  - footnotes
  # Annotations, Grids, Images
  - md_in_html
  # Images
  - pymdownx.blocks.caption
  # Formatting
  - pymdownx.caret
  # Formatting
  - pymdownx.critic
  # Admonitions
  - pymdownx.details
  # Icons & Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji ''
      emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
  # Code Blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  # Code Blocks
  - pymdownx.inlinehilite
  # Formatting
  - pymdownx.keys
  # Formatting
  - pymdownx.mark
  # Code Blocks, Tooltips
  - pymdownx.snippets
  # Admonitions, Annotations, Code Blocks, Content Tabs
  - pymdownx.superfences
  # Content Tabs
  - pymdownx.tabbed:
      alternate_style: true
  # Lists
  - pymdownx.tasklist:
      custom_checkbox: true
  # Formatting
  - pymdownx.tilde
  # Data Tables

  - toc:
      permalink: true

plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      puml_keyword: plantuml
  - minify:
      minify_html: true
  - search
  - mkdocs-jupyter:
      execute: false
      allow_errors: true

theme:
  favicon: assets/ibmec_icon.png
  name: material
  logo: assets/ibmec_logo.png
  palette:
    
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: black
      toggle:
        icon: material/toggle-switch-off
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: amber
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
      color_mode: dark
      language: pt-BR
      favicon: images/favicon.png
      user_color_mode_toggle: true
  
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    logo: simple/react
    favicon: simple/react
