# Generated by Django 5.1.2 on 2025-05-16 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('1', 'Domicílio Particular Permanente'), ('5', 'Domicílio Particular Improvisado'), ('6', 'Domicílio Coletivo com Morador')], max_length=1)),
                ('tipo', models.CharField(choices=[('011', 'Casa'), ('013', 'Apartamento')], max_length=3)),
                ('abastecimento_agua', models.CharField(max_length=1)),
                ('banheiros', models.PositiveIntegerField()),
                ('destino_esgoto', models.CharField(max_length=1)),
                ('coleta_lixo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Falecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_falecimento', models.DateField()),
                ('idade_falecimento', models.PositiveIntegerField()),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basico.domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('1', 'Masculino'), ('2', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('idade', models.PositiveIntegerField()),
                ('parentesco', models.CharField(max_length=2)),
                ('raca_cor', models.CharField(choices=[('1', 'Branca'), ('2', 'Preta'), ('3', 'Amarela'), ('4', 'Parda'), ('5', 'Indígena')], max_length=1)),
                ('considera_indigena', models.BooleanField(null=True)),
                ('etnia_indigena', models.CharField(blank=True, max_length=100)),
                ('fala_lingua_indigena', models.BooleanField(null=True)),
                ('alfabetizado', models.BooleanField(null=True)),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moradores', to='basico.domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renda_mensal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('faixa_rendimento', models.CharField(max_length=1)),
                ('morador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basico.morador')),
            ],
        ),
    ]
