@startuml


class Cliente {
  
}

class Carrinho {
  
  
}

class ItemCarrinho {
  
}

class Produto {

}

class Pedido {
 
}

class ItemPedido {
 
}


Cliente  -- Endereco
Cliente  --  Carrinho
Cliente  --  Pedido

Carrinho -- ItemCarrinho
ItemCarrinho -- Produto

Pedido  -- Endereco
Pedido --  FormaPagamento
Pedido  --  ItemPedido
Pedido  --  Entrega

ItemPedido  --  Produto
FormaPagamento -- Pagamento
Pagamento -- SistemaPagamento
Entrega -- ServicoEntrega

@enduml
